#server:
#  port: 8000

spring:
#  application:
#    name: passjava-channel

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/passjava_chms?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456

#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:1111
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
